// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjjjzfhxecqlkeojjadg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqamp6Zmh4ZWNxbGtlb2pqYWRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NzMxNTksImV4cCI6MjA2NDA0OTE1OX0.cuW419SOEWS26IDCqhYOT0Xl_P2MAKwYFqG2O56gOsk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);